### ISSUE TITLE
Add http://imolarpg.dyndns.org/trac/balatest/browser/branches/BAR/luaui/widgets/dbg_err_console.lua

### ISSUE THREAD

**Issue by silentwings** [SpringCabal/SkeletonGame#14]
because it really is _that_ awesome.

**Comment by gajop** [comment]
A solution to the second requirement of https://github.com/SpringCabal/SkeletonGame/issues/7

**Comment by silentwings** [comment]
No; it only displays errors/warnings.

**Comment by gajop** [comment]
I'll leave adding this file to you.
