### ISSUE TITLE
Consider default turnAccel

### ISSUE THREAD

**Issue by GoogleFrog** [SpringCabal/SkeletonGame#19]
The default turnAccel in the engine leads to sluggish unit behaviour. I think it should be set to a larger value by default.

**Comment by GoogleFrog** [comment]
Add this gadget:
- https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/unit_turn_without_interia.lua

Depends on:
- https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaRules/Gadgets/unit_turn_without_interia.lua

**Comment by gajop** [comment]
I assume the dependency you were referring to is https://github.com/SpringCabal/SkeletonGame/blob/5df32771d6146133fe2cd32ade7ebf01e2e41d43/LuaRules/Utilities/unitTypeChecker.lua and added in the previous commit. Please correct me if I'm wrong.
