### ISSUE TITLE
engine sound errors 

### ISSUE THREAD

**Issue by gajop** [SpringCabal/SkeletonGame#21]
We don't have default sounds for selecting units and similar engine operations (https://github.com/spring/spring/blob/develop/cont/base/springcontent/gamedata/sounds.lua)
Even removing those sound defs will produce new errors.

[f=-000001] [Sound] Error: Unable to open audio file: sounds/button9.wav
and
[f=-000001] [Sound] Error: Unable to open audio file: FailedCommand
[f=-000001] [Sound] Error: CSound::GetSoundId: could not find sound: FailedCommand

**Comment by greze** [comment]
I can look into making some default sounds

**Comment by gajop** [comment]
Feel free to do so. It's not a high priority (I just want to get rid of all the errors), but doing it might get you more familiar with the environment.

**Comment by gajop** [comment]
For clarity, this still doesn't cover FailedCommand (which wasn't even defined before).
[f=-000001] [Sound] Error: Unable to open audio file: FailedCommand
[f=-000001] [Sound] Error: CSound::GetSoundId: could not find sound: FailedCommand

Seeing as the next LD is tomorrow it's OK to ignore this for now.
